ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS companies_checked INTEGER NOT NULL DEFAULT 0;
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS postings_fetched INTEGER NOT NULL DEFAULT 0;
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS duplicates_removed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS excluded_location INTEGER NOT NULL DEFAULT 0;
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS excluded_arrangement INTEGER NOT NULL DEFAULT 0;
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS excluded_experience INTEGER NOT NULL DEFAULT 0;
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS warnings TEXT;
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS run_kind TEXT NOT NULL DEFAULT 'sample';

CREATE TABLE IF NOT EXISTS source_cache (
  cache_key TEXT PRIMARY KEY,
  body TEXT NOT NULL,
  fetched_at TIMESTAMPTZ NOT NULL
);
